# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\source\vscode repos\seabed-imaging\ui\about.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(708, 615)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tb_header = QtWidgets.QTextBrowser(self.centralwidget)
        self.tb_header.setGeometry(QtCore.QRect(-1, 0, 711, 111))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.tb_header.setFont(font)
        self.tb_header.setObjectName("tb_header")
        self.back_button = QtWidgets.QPushButton(self.centralwidget)
        self.back_button.setGeometry(QtCore.QRect(600, 490, 93, 81))
        self.back_button.setObjectName("back_button")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(20, 120, 671, 451))
        font = QtGui.QFont()
        font.setFamily("Mistral")
        font.setPointSize(16)
        font.setItalic(False)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.tb_header.raise_()
        self.plainTextEdit.raise_()
        self.back_button.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 708, 26))
        self.menubar.setObjectName("menubar")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        self.menu_edit = QtWidgets.QMenu(self.menubar)
        self.menu_edit.setObjectName("menu_edit")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_window = QtWidgets.QMenu(self.menubar)
        self.menu_window.setObjectName("menu_window")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.action_open = QtWidgets.QAction(MainWindow)
        self.action_open.setObjectName("action_open")
        self.action_save = QtWidgets.QAction(MainWindow)
        self.action_save.setObjectName("action_save")
        self.menu_file.addAction(self.action_open)
        self.menu_file.addAction(self.action_save)
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_edit.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_window.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tb_header.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Comic Sans MS\'; font-size:7.8pt; font-weight:400; font-style:normal;\" bgcolor=\"#d0ecf8\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:18pt;\">   </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:18pt; font-weight:600;\">JsfReader</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:18pt;\">   Помощь</span></p></body></html>"))
        self.back_button.setText(_translate("MainWindow", "<-"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "1) Если ваш файл не корректно отображается попробуйте изменить режим отрисовки или поменять масштаб отрисованного изображения, так же удостоверьтесь в корректности переданных данных.\n"
"2) Если программа выдеёт ошибку при работе, пожалуйста, удостоверьтесь что файл не повреждён и данные в нём корректны.\n"
"3) Учтите, что обработка файлов большого размера может занять несколько минут, во это время приложением нельзя будет пользоваться. В таком случае, пожалуйста, наберитесь терпения и дождитесь загрузки.\n"
"4) Если ваша ситуация не решилась или у вас имеются иные проблемы вы можете обратиться за помощью в поддержку - jsf.support@mail.ru"))
        self.menu_file.setTitle(_translate("MainWindow", "Файл"))
        self.menu_edit.setTitle(_translate("MainWindow", "Правка"))
        self.menu.setTitle(_translate("MainWindow", "Вид"))
        self.menu_window.setTitle(_translate("MainWindow", "Окно"))
        self.menu_2.setTitle(_translate("MainWindow", "Справка"))
        self.action_open.setText(_translate("MainWindow", "Открыть"))
        self.action_save.setText(_translate("MainWindow", "Сохранить"))
